### ISSUE TITLE
File Path to Dictionary

### ISSUE THREAD

**Issue by ullrichd21** [cmpsc-481-s22-m1/GatorConfig#5]
**What is the task**
Convert list of file paths to dictionary

**Describe the solution you'd like**
Would like to provide a list of file paths and get a YAML similar to this:
```
src/main:
    java:
        samplelab/SampleLabMain.java:
        samplelab/DataClass.java:
```

**Time estimation**
2Hrs

**Additional context**
